// LOCALHOST 
### GET 
http://localhost:8080/recipes
### GET 
http://localhost:8080/recipes/652af122d08ad515db13a273
### GET 
http://localhost:8080/recipes/652af960d08ad515db13a275
### GET 
http://localhost:8080/recipes/652af99dd08ad515db13a276



### POST Create Recipe 
POST http://localhost:8080/recipes HTTP/1.1
content-Type: application/json

{
  "dishName": "Tacos de Lengua",
  "prepTime": "10 min",
  "cookTime": "20 min",
  "yield": "12 tacos",
  "mealType": "Main Dish"
}

### PUT Update Recipe 
PUT http://localhost:8080/recipes/65347b0b98c3b875ccb08e90 HTTP/1.1
content-Type: application/json

{
  "dishName": "Tacos de Suadero",
  "prepTime": "10 min",
  "cookTime": "20 min",
  "yield": "12 tacos",
  "mealType": "Main Dish"
}

### POST Create User 
POST http://localhost:8080/signup/ HTTP/1.1
content-Type: application/json

{
  "username": "Nefi Perez",
  "password": "123"
}

### POST LogIn user
POST http://localhost:8080/login/ HTTP/1.1
content-Type: application/json

{
  "username": "Nefi Perez",
  "password": "123"
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// PRODUCTION Deploy 

### GET 
https://recipe-builder-app.onrender.com/recipes
### GET 
https://recipe-builder-app.onrender.com/recipes/652af122d08ad515db13a273
### GET 
https://recipe-builder-app.onrender.com/recipes/652af960d08ad515db13a275
### GET 
https://recipe-builder-app.onrender.com/recipes/652af99dd08ad515db13a276


### POST Create Contact 
POST https://recipe-builder-app.onrender.com/recipes HTTP/1.1
content-Type: application/json

{
  "dishName": "Flan",
  "prepTime": "15 min",
  "cookTime": "50 min",
  "yield": "12 servings",
  "mealType": "Desserts"
}

### PUT Update Contact 
PUT https://recipe-builder-app.onrender.com/recipes/652af99dd08ad515db13a276 HTTP/1.1
content-Type: application/json

{
  "dishName": "",
  "prepTime": "",
  "cookTime": "",
  "yield": "",
  "mealType": ""
}

### DELETE Update Contact 
DELETE https://recipe-builder-app.onrender.com/recipes/652af99dd08ad515db13a276 HTTP/1.1
